### ISSUE TITLE
American Numismatic Society IIIF manifest URLs incorrectly formed & not displaying

### ISSUE THREAD

**Issue by caaster** [sul-dlss/dlme#796] opened 2019-12-10 18:45 UTC
See: https://spotlight.dev.dlmenetwork.org/library/catalog?q=agg_is_shown_at.wr_is_referenced_by_ssi%3A%5B%2A+TO+%2A%5D&search_field=all_fields

@cvilla or @mejackreed can likely consult with recs of how to best work with the contributor to resolve this issue

**Comment by cbeer** [comment] 2019-12-10 18:47
Duplicate of https://github.com/sul-dlss/dlme/issues/795.

**Closed by cbeer** 2019-12-10 18:47 UTC
