### ISSUE TITLE
Total record count doesn't match when facet is active

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/dlme#1677] opened 2023-02-17 21:41 UTC
Currently visible on the old dev site (but not old prod): https://dev.dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=American+University+in+Cairo

![Screenshot 2023-02-17 at 13 40 13](https://user-images.githubusercontent.com/4924494/219799067-9609fa88-5940-46ad-a6ed-c43ba91266d1.png)

**Comment by thatbudakguy** [comment] 2023-02-17 21:41
worth checking if there is a config difference between old dev and old prod, since it may never have manifested in prod.

**Comment by corylown** [comment] 2023-02-22 16:54
The only difference I can find between the solr config on prod and dev is in the `updateHandler`

### Prod
```
  <updateHandler class="solr.DirectUpdateHandler2">
    <updateLog>
      <str name="dir">${solr.core0.data.dir:}</str>
    </updateLog>
  </updateHandler>
```

### Dev
```
  <updateHandler class="solr.DirectUpdateHandler2">
    <updateLog>
      <str name="dir">${solr.core0.data.dir:}</str>
    </updateLog>
    <autoCommit>
       <maxDocs>20000</maxDocs>
       <maxTime>15000</maxTime>
       <openSearcher>false</openSearcher>
    </autoCommit>
    <autoSoftCommit>
      <maxTime>900000</maxTime>
    </autoSoftCommit>
    <commitWithin>
      <softCommit>false</softCommit>
    </commitWithin>
  </updateHandler>
```

**Comment by thatbudakguy** [comment] 2023-02-22 18:43
hmm. if one environment was committing more slowly because it didn't have autocommit thresholds set up, that could explain some of why this was hard to track down and only manifested after an initial load — the commit was triggered in one environment but not another, but then loading more data caused it to commit and so the problem went away.

as of right now I'd assume that stage and prod have the same core config, so if this does manifest it should at least be in both environments.

**Comment by jcoyne** [comment] 2023-02-22 19:33
If you issue a commit to solr, does the problem disappear?

**Comment by thatbudakguy** [comment] 2023-02-22 20:09
just issued a commit, but the problem seems to persist.

**Comment by thatbudakguy** [comment] 2023-02-22 20:12
facet counts from solr match the counts in the sidebar:

![Screenshot 2023-02-22 at 12 12 28](https://user-images.githubusercontent.com/4924494/220748290-8e107844-46eb-4aee-973e-ef07f7117d4e.png)

**Comment by corylown** [comment] 2023-02-23 20:44
Huda found that changing facet.method from the default of fc to enum produces the correct count.

`facet.method=fc`
```
{
  "responseHeader":{
    "zkConnected":true,
    "status":0,
    "QTime":2,
    "params":{
      "q":"*:*",
      "facet.field":"agg_data_provider_ssim",
      "fl":"id,agg_data_provider_ssim",
      "facet.method":"fc",
      "fq":"agg_data_provider_ssim:\"Brooklyn Museum\"",
      "rows":"0",
      "facet":"on"}},
  "response":{"numFound":8388,"start":0,"numFoundExact":true,"docs":[]
  },
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{
      "agg_data_provider_ssim":[
        "Brooklyn Museum",5587,
        "متحف بروكلين",5587]},
    "facet_ranges":{},
    "facet_intervals":{},
    "facet_heatmaps":{}}}
 ```
`facet.method=enum`
```
    {
  "responseHeader":{
    "zkConnected":true,
    "status":0,
    "QTime":9,
    "params":{
      "q":"*:*",
      "facet.field":"agg_data_provider_ssim",
      "fl":"id,agg_data_provider_ssim",
      "facet.method":"enum",
      "fq":"agg_data_provider_ssim:\"Brooklyn Museum\"",
      "rows":"0",
      "facet":"on"}},
  "response":{"numFound":8388,"start":0,"numFoundExact":true,"docs":[]
  },
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{
      "agg_data_provider_ssim":[
        "Brooklyn Museum",8388,
        "متحف بروكلين",8388]},
    "facet_ranges":{},
    "facet_intervals":{},
    "facet_heatmaps":{}}}
```
Relevant Solr documentation: https://solr.apache.org/guide/solr/latest/query-guide/faceting.html#field-value-faceting-parameters

**Comment by thatbudakguy** [comment] 2023-02-23 20:57
The docs on `enum` say:
> This method is recommended for faceting multi-valued fields that have only a few distinct values.

> For example, faceting on a field with U.S. States such as Alabama, Alaska, …​ Wyoming would lead to fifty cached filters which would be used over and over again. The filterCache should be large enough to hold all the cached filters.

This does sound relatively similar to the situation for data providers (~20 values) but I don't know if it applies to all our facet fields.

The docs also say:

>Unless otherwise specified, all of the parameters below can be specified on a per-field basis with the syntax of `f.<fieldname>.facet.<parameter>`

So I wonder if the thing to do here is to make sure we pass `f.agg_data_provider_ssim.facet.method:enum` at query-time so we're only using that method for the one facet.

**Comment by corylown** [comment] 2023-02-23 21:02
@thatbudakguy what I still don't understand is _why_ these methods produce different results. I'd expect a performance difference maybe, but not a different answer. Since this is only happening in the AWS dev environment I'm tempted to leave things as they are and if we see the issue appear elsewhere we continue the investigation or switch the facet method.

**Comment by jcoyne** [comment] 2023-02-23 22:03
> I still don't understand is why these methods produce different results

It's hard (expensive) to accurately count large numbers of results precisely in a system where there are shards distributed across a number of machines and the number of distinct values is also high.  This is a tradeoff for speed.  Our corpus and distinct values for this facet are probably small enough that you won't notice the performance impact. See https://searchengineland.com/why-google-cant-count-results-properly-53559

**Comment by hudajkhan** [comment] 2023-02-28 18:10
What finally worked:
a) Outputting the Solr documents, deleting all the document, and then re-uploading them.
b) Clearing the Rails cache so that the facet counts when you first load the front page match what you see when you select a facet and match the Solr index  counts. 

Facet counts seem to finally be consistent with resulting row count when a facet is selected.

**Comment by hudajkhan** [comment] 2023-02-28 21:02
Given that we have not been able to reproduce this error on a local machine, and we no longer see that error once we've re-indexed the data from scratch, we will be closing this issue now but will keep an eye out for any similar behavior in the future.  It is still unclear what caused the original facet count error. If the issue manifests again, we can revisit this ticket.

**Closed by hudajkhan** 2023-02-28 21:02 UTC
Labels: bug, wontfix
