### ISSUE TITLE
Cartographic Display does not have a viewer

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#122] opened 2017-08-21 13:56 UTC
For cartographic resources (e.g. http://staging.dlme.clir.org/library/catalog/stanford_gk628xr0233) there should be a viewer embedded (e.g. https://purl.stanford.edu/gk628xr0233) to preview the dataset.

**Comment by cbeer** [comment] 2017-08-21 14:35
This is a duplicate of the javascript error causing #119.

**Closed by cbeer** 2017-08-21 14:35 UTC
