### ISSUE TITLE
Spacing of Arabic calendar label and radio buttons

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1139] opened 2021-01-21 15:12 UTC
In all views the Arabic translation of the 'calendar' label is all the way to the right edge. A bit more visual separation is needed.
<img width="968" alt="Screen Shot 2021-01-21 at 10 08 29 AM" src="https://user-images.githubusercontent.com/37662787/105369951-0bd91280-5bd1-11eb-9273-e9f17ab26b34.png">

In the smallest viewports the radio buttons also need spacing.
<img width="570" alt="Screen Shot 2021-01-21 at 10 03 15 AM" src="https://user-images.githubusercontent.com/37662787/105369999-1abfc500-5bd1-11eb-8399-a010455aebb8.png">

**Comment by mejackreed** [comment] 2021-01-21 15:51
Is this a duplicate of #1137 ?

**Comment by jacobthill** [comment] 2021-01-21 15:59
I thought we had a ticket for that somewhere. Yes, but the radio buttons are new. I'll paste my screenshot into that ticket.

**Closed** 2021-01-21 16:00 UTC
Labels: bug, design needed
